ArticleList
omar-baggio/Solo-Project-Front-End pull request #1
Opened 2023-07-17 15:33 UTC by omar-baggio

2023-07-17 15:48 UTC, B7Bprog requested changes
Hey Omar, please see my comments, refactor your code, then send us another PR with it.

2023-07-17 15:48 UTC, B7Bprog commented on Utils/api.js
> +    console.log(articles, "<--- res in api");
Please remove all logs.

2023-07-17 15:48 UTC, B7Bprog commented on src/components/ArticlesList.jsx
> +      console.log(dataFromApi, "<--- articles in articleList");
Don't need this log either.

2023-07-17 15:48 UTC, B7Bprog commented on src/components/ArticlesList.jsx
> +  const [articles, setArticles] = useState([]);
Please add a state for errors and one for a 'loading' indication and please make sure it displays those messages in the appropriate cases.

2023-07-17 15:48 UTC, B7Bprog commented on src/components/ArticlesList.jsx
> +          <section key={article.article_id} className="articlesbox">
This part could be extracted into a separate component.

2023-07-17 15:48 UTC, B7Bprog commented on src/App.css
> +}
Please think about a responsive design, where the screen size is considered.

2023-07-18 08:48 UTC, NRMSMITH commented
Excellent implementation of the feedback ! I'm happy for you to merge this 👍

2023-07-18 08:51 UTC, merged