Ticket 7
omar-baggio/Solo-Project-Front-End pull request #4
Opened 2023-07-18 13:56 UTC by omar-baggio

2023-07-18 14:07 UTC, NRMSMITH requested changes
Your user is able to increment on the website ... but this doesn't impact the backend at all!  You will need to make an API call to increase the votes on the db so that the vote persists!

2023-07-18 14:07 UTC, NRMSMITH commented on src/components/Votes.jsx
> +
You might want to consider putting in functionality so that they are able to _undo_ a mistaken vote! :)

2023-07-18 14:07 UTC, NRMSMITH commented on src/components/Votes.jsx
> +  };
is there a way that you could make increase and decrease into _one_ function?:)

2023-07-19 09:17 UTC, itskatherine requested changes
Great functionality on the vote buttons, I like that you can toggle upvoting and downvoting an article. A couple more things to think about though - can you please have a look at my comments and resubmit this PR once you've addressed them 🙂

2023-07-19 09:17 UTC, itskatherine commented on src/components/Votes.jsx
>      }
To reiterate what Niamh's said 👇 I see a lot of repeating code with different inputs in the `increase` and `decrease` functions - this could be a good case to refactor them into one function 💭

2023-07-19 09:17 UTC, itskatherine commented on src/components/Votes.jsx
> +      setVoteChange(-1);
We need to let the user know (by correcting the state) if a API request has failed or not gone through.
Consider how you can use a `catch` block on your API calls to do this, the [notes may help](https://notes.northcoders.com/courses/js-front-end/ui-behaviours-and-optimistic-rendering#error-handling)

2023-07-19 11:05 UTC, B7Bprog requested changes
Hey Omar, please see my comment and try to implement it. Once it's done, please send us a PR with it.

2023-07-19 11:05 UTC, B7Bprog commented on src/components/Votes.jsx
> +      patchArticle(newArticle.article_id, changeValue);
As it was mentioned in previous comments, when something goes wrong and there's an error when patching the votes, an error message should be displayed and the number of votes should be reverted to the amount before the click. You can set this up in a catch() block.

2023-07-20 10:11 UTC, itskatherine reviewed
Hi Omar, great work refactoring it into one function 🙌 
Seems to be working well in almost all cases - the one thing is it's giving an error message when you undo a vote, even when it's working as it should
Once you've fixed this - you're good to merge 👍

2023-07-20 10:11 UTC, itskatherine commented on src/components/Votes.jsx
> +          setErr("Something went wrong, please try again.");
This line here and on line 21 is causing this message to happen when you undo a vote - though it seems to be working fine!

2023-07-20 10:19 UTC, merged