complete ticket 8
omar-baggio/Solo-Project-Front-End pull request #5
Opened 2023-07-20 11:00 UTC by omar-baggio

2023-07-20 13:12 UTC, B7Bprog requested changes
Hey Omar, please correct/implement the following and send us another PR when it's all done:

- Have a logged in user.
- Only that logged-in user can post a comment
- Update the list of comments, so the freshly posted comments appear.
- One input should be enough for the body of the comment. 
- Instead of an input tag, please use the textarea tag so it will allow the user to add multiline comments.
- The 'Post' button should be disabled for the time of posting, to avoid posting the same comment multiple times.
- Clear the input field after a post.

2023-07-21 09:01 UTC, itskatherine reviewed
Hi Omar, really great progress love the login functionality 🙌 
A couple of things to look at though - can you please address them and then put in another PR 🙂

2023-07-21 09:01 UTC, itskatherine commented on Utils/api.js
> +    console.log(users, "users in api");
`console.log` begone

2023-07-21 09:01 UTC, itskatherine commented on src/components/AddComment.jsx
> +        setComments((currentComment) => [commentFromApi, ...currentComment]);
The state is not being correctly updated at the moment - though the API request is working correctly as it looks correct when the page is refreshed 🔍 
Side not can you please add an s so it's `currentComments` 🙏 
I suggest having a look at the `currentComments` and the `commentFromApi` - something is stopping the `commentFromApi` being added to the list correctly 🕵️‍♂️

2023-07-21 09:01 UTC, itskatherine commented on src/Context/UserContext.jsx
> +
Nice use of context, cool login functionality 🙌

2023-07-21 09:01 UTC, itskatherine commented on src/components/AddComment.jsx
> +        setError("Something went wrong, please try again.");
Great that you're updating your error state, but you still need to use it to let the user know their post hasn't gone through if there's a problem (i.e. the internet stops). Can you add an error message that the user can see please 🙂

2023-07-21 09:01 UTC, itskatherine commented on src/components/AddComment.jsx
> +        </form>
The user can currently mash the post button and post loads of empty comments - can you add some form validation to this page please to prevent this

2023-07-21 12:52 UTC, itskatherine reviewed
Hi Omar, nice additional functionality - I have a few other points to look over
Once you've addressed my comments, you're good to merge 👍

2023-07-21 12:52 UTC, itskatherine commented on src/components/AddComment.jsx
> +      ) : (
I'm still finding I'm able to submit empty comments I'm afraid 😢

2023-07-21 12:52 UTC, itskatherine commented on src/components/AddComment.jsx
> +      });
I'm a fan of disabling the button, one thing to add though is to un-disable the button once the user can make another comment! I.e. once the previous comment has gone through and  they've written something in the text box!
Great addition of the error message to let the user know there's been a problem 👍

2023-07-21 13:26 UTC, merged